import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import bg2 from '../public/images/bg.png'

import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Circles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className=' w-3/4 h-1/2 absolute flex justify-center'>
      <button className='h-10 pb-3 mt-48 inline-flex items-center text-center justify-center rounded-md p-2 text-gray-400 bg-green-600  hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white
'>zzzzzzzzz</button>
      </div> 
      <Image src={bg2} className="w-full h-full bg-cover "/>
     
        </div>
    </>
  )
}
