import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import bg from '../public/images/bg.png'

import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Circles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-bg">
      <Image width={90} height={90} src={bg} className="scale-125 object-fill flex"/>

        <h1>Helping people find safe social spaces</h1>
       
        </div>
    </>
  )
}
