import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSession, signOut, signIn } from "next-auth/react";
import LP2 from "../public/images/LP2.svg";
import Logoblack from "../public/images/LogoBlack.png";

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();
  console.log("session on index", session);

  return (
    <div className="relative font-mons">
      <Head>
        <title>Circles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative ">
        {/* <img src={bg2} className="w-full h-full bg-cover"/> */}

      //  <Image src={LP2} className="w-full h-full bg-cover" />
        <div className='absolute w-[300px] h-[300px] bottom-44' >
        
        <h1 className=' transition ease-in delay-300 duration-300 opacity-100 absolute w-[1000px] left-[200px] bottom-96 text-6xl '
        >"Helping people access their local community through social prescriptions."</h1>
          <div className='absolute w-[300px] h-[150px] left-[950px]'>

            <Image width={250} height={250} src={Logoblack} className='absolute w-[300px] h-[125px]' />
        
            <div className=' absolute w-28 left-[70px] top-[110px]  rounded-md  bg-[#A3DCEF] transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-[#FFD862] duration-300
' >
          {session ? (''
        ) : (
          <button
            className="flex pl-7 "
            onClick={() => {
              signIn();
            }}
          >
            Sign in
          </button>
        )}

            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
